# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import leetcode167 as module_0


#@pytest.mark.xfail(strict=True)
def test_case_0(): #FAILED test_leetcode167.py::test_case_0 - TypeError: '<' not supported between instances of 'int' and 'NoneType'
    bool_0 = True
    bool_1 = True
    list_0 = [bool_0, bool_1]
    none_type_0 = None
    solution_0 = module_0.Solution()
    solution_0.twoSum(list_0, none_type_0)


def test_case_1(): #PASSED
    bool_0 = False
    list_0 = [bool_0]
    bool_1 = True
    solution_0 = module_0.Solution()
    list_1 = solution_0.twoSum(list_0, bool_1)
    solution_1 = module_0.Solution()
    list_2 = []
    list_3 = solution_1.twoSum(list_2, solution_1)


#@pytest.mark.xfail(strict=True)
def test_case_2(): #FAILED test_leetcode167.py::test_case_2 - TypeError: Solution() takes no arguments
    str_0 = ")yN*0Qj dp>k<-bo%eRW"
    dict_0 = {str_0: str_0}
    module_0.Solution(**dict_0)


def test_case_3(): #PASSED
    bool_0 = False
    int_0 = -1163
    int_1 = 2619
    list_0 = [bool_0, int_0, int_1]
    list_1 = []
    solution_0 = module_0.Solution(*list_1)
    list_2 = solution_0.twoSum(list_0, int_0)


def test_case_4(): #PASSED
    solution_0 = module_0.Solution()
    dict_0 = {}
    int_0 = -1066
    int_1 = -5525
    int_2 = -2927
    list_0 = [int_0, int_1, int_2]
    int_3 = -473
    list_1 = solution_0.twoSum(list_0, int_3)
    solution_1 = module_0.Solution()
    list_2 = solution_1.twoSum(dict_0, int_0)
