# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import cod as module_0
#https://github.com/gahogg/Leetcode-Solutions/blob/main/Word%20Search%20-%20Leetcode%2079/Word%20Search%20-%20Leetcode%2079.py

# @pytest.mark.xfail(strict=True)
def test_case_0():#XFAIL FAILED test_cod.py::test_case_0 - KeyError: 0
    int_0 = 493
    dict_0 = {int_0: int_0, int_0: int_0, int_0: int_0, int_0: int_0}
    none_type_0 = None
    list_0 = []
    list_1 = [list_0]
    str_0 = ""
    bool_0 = module_0.exist(list_1, str_0)
    assert bool_0 is False
    module_0.exist(dict_0, none_type_0)


def test_case_1():#PASSED
    str_0 = "=iJXwnH\x0c%}!$f"
    list_0 = [str_0, str_0, str_0]
    list_1 = [list_0, list_0, list_0]
    bool_0 = module_0.exist(list_1, list_0)
    assert bool_0 is True


# @pytest.mark.xfail(strict=True)
def test_case_2():#XFAIL FAILED test_cod.py::test_case_2 - TypeError: object of type 'int' has no len()
    bytes_0 = b"k\xca"
    module_0.exist(bytes_0, bytes_0)


# @pytest.mark.xfail(strict=True)
def test_case_3():#XFAIL FAILED test_cod.py::test_case_3 - IndexError: list index out of range
    str_0 = "Cn\t]>\x0b"
    str_1 = "|g94,0"
    list_0 = [str_0, str_1, str_1]
    list_1 = [str_0, str_0, str_0]
    list_2 = [list_0, list_1]
    bool_0 = module_0.exist(list_2, list_1)
    assert bool_0 is True
    str_2 = "Uh"
    str_3 = "B"
    str_4 = ""
    bool_1 = module_0.exist(str_3, str_4)
    assert bool_1 is False
    list_3 = []
    module_0.exist(list_3, str_2)


def test_case_4():#PASSED
    str_0 = "_u"
    str_1 = 'pE&Qw=g]8\x0cd"{Mp'
    list_0 = [str_0, str_0, str_1]
    list_1 = [list_0, list_0, list_0, list_0]
    bool_0 = module_0.exist(list_1, str_1)
    assert bool_0 is False


def test_case_5():#PASSED
    str_0 = "\n"
    str_1 = ';g!ogEF[?"bc6j;meS0'
    str_2 = '"gaqAPoa\nN)705gc1\r\r'
    str_3 = "wC&=7b@!^\x0c_\r8Ob@2~6"
    list_0 = [str_2, str_1, str_0, str_3]
    list_1 = [list_0]
    bool_0 = module_0.exist(list_1, str_3)
    assert bool_0 is False
    list_2 = [str_0, str_1, str_1]
    list_3 = [list_2, list_2, list_2, list_2]
    str_4 = "zLc%\x0c\n"
    bool_1 = module_0.exist(list_3, str_4)
    assert bool_1 is False
    bool_2 = module_0.exist(list_1, list_2)
    assert bool_2 is False
    str_5 = '"gaqAPoa\nN)705gc1\r\r'
    bool_3 = module_0.exist(list_3, str_5)
    assert bool_3 is False


# @pytest.mark.xfail(strict=True)
def test_case_6():#XFAIL FAILED test_cod.py::test_case_6 - IndexError: list index out of range
    str_0 = "Cn\t]>\x0b"
    str_1 = "|g94,0"
    str_2 = "tidhD:M;"
    list_0 = [str_0, str_1, str_2]
    list_1 = [str_1, str_1, str_0, str_0, str_0]
    list_2 = [list_0, list_1]
    bool_0 = module_0.exist(list_2, list_1)
    assert bool_0 is False
    str_3 = "Uh"
    str_4 = "B"
    str_5 = ""
    bool_1 = module_0.exist(str_4, str_5)
    assert bool_1 is False
    list_3 = []
    module_0.exist(list_3, str_3)
